// Generates the bloodshot veins for the DMG window background and writes them into background.html,
// between the <!-- veins:start --> and <!-- veins:end --> markers.
// Usage: node script/dmg/veins.mjs script/dmg/background.html 11
// Same seeded branching generator as site/art/veins.mjs: veins root on the window edges and creep
// toward the centre; the centre (icons, labels, arrow: x 90-570, y 90-330) is masked clean.
import fs from 'node:fs';
const [,, target, seedArg = '11'] = process.argv;
let seed = Number(seedArg);
const rnd = () => ((seed = (seed * 1664525 + 1013904223) >>> 0) / 4294967296);
const R = (a, b) => a + (b - a) * rnd();
const W = 660, H = 420;

const polys = { v: [], c: [] };
let MINW = 0.3, into = 'v'; // capillaries taper finer and go into their own layer
function vein(x, y, ang, len, w0, depth) {
  const pts = [];
  let a = ang, s = 0, px = x, py = y;
  const phase = R(0, 6.28), freq = R(0.08, 0.18), amp = R(0.07, 0.13);
  const forks = [];
  const nf = depth === 0 ? 2 + Math.floor(R(0, 3)) : depth === 1 ? (rnd() < 0.6 ? 1 : 0) : 0;
  for (let i = 0; i < nf; i++) forks.push(R(0.2, 0.7) * len);
  forks.sort((p, q) => p - q);
  const step = 2;
  while (s <= len) {
    const w = MINW + (w0 - MINW) * Math.pow(1 - s / len, 0.9);
    pts.push([px, py, a, w]);
    if (forks.length && s >= forks[0]) {
      forks.shift();
      vein(px, py, a + (rnd() < 0.5 ? -1 : 1) * R(0.35, 0.8), (len - s) * R(0.45, 0.8) + 3, Math.max(0.4, w * 0.72), depth + 1);
    }
    a += Math.sin(s * freq + phase) * amp + R(-0.03, 0.03);
    a = ang + Math.max(-0.65, Math.min(0.65, a - ang));
    px += Math.cos(a) * step; py += Math.sin(a) * step; s += step;
  }
  const L = [], Rr = [];
  for (const [x1, y1, a1, w] of pts) {
    const nx = -Math.sin(a1) * w / 2, ny = Math.cos(a1) * w / 2;
    L.push([x1 + nx, y1 + ny]); Rr.push([x1 - nx, y1 - ny]);
  }
  const f = (n) => Math.round(n * 10);
  const all = L.concat(Rr.reverse()).map(([a1, b1]) => [f(a1), f(b1)]);
  const num = (n) => (n < 0 ? '-' : ' ') + (Math.abs(n) / 10).toString().replace(/^0\./, '.');
  let d = `M${all[0][0] / 10} ${all[0][1] / 10}l`;
  for (let i = 1; i < all.length; i++) d += num(all[i][0] - all[i - 1][0]) + num(all[i][1] - all[i - 1][1]);
  polys[into].push(d.replace('l ', 'l') + 'z');
}

// A point on the window edge and the inward direction, for t in [0, 1) around the perimeter.
const P = 2 * (W + H);
const edge = (t) => {
  const d = ((t % 1) + 1) % 1 * P;
  if (d < W) return [d, -1, Math.PI / 2];
  if (d < W + H) return [W + 1, d - W, Math.PI];
  if (d < 2 * W + H) return [W - (d - W - H), H + 1, -Math.PI / 2];
  return [-1, H - (d - 2 * W - H), 0];
};
// Distance from a point to the centre box, measured along the inward direction.
const reach = (x, y) => {
  const dx = Math.max(90 - x, x - 570, 0), dy = Math.max(90 - y, y - 330, 0);
  return Math.max(dx, dy);
};

// Main veins: roots spaced unevenly around the whole rim, a little denser toward the corners.
for (let t = R(0, 0.02); t < 1; t += R(0.026, 0.05)) {
  const [x, y, a] = edge(t);
  const corner = Math.min(Math.hypot(x, y), Math.hypot(W - x, y), Math.hypot(x, H - y), Math.hypot(W - x, H - y));
  const toCorner = corner < 150 ? (rnd() < 0.5 ? 1 : -1) * R(0.2, 0.55) : R(-0.35, 0.35);
  vein(x, y, a + toCorner, reach(x, y) * R(0.5, 1.0) + (corner < 150 ? 24 : 0), R(1.7, 2.8), 0);
}

// Capillaries: a dense web of short, hair-thin, faint pink vessels under the main veins.
MINW = 0.16; into = 'c';
for (let t = 0; t < 1; t += R(0.0025, 0.0045)) {
  const [x, y, a] = edge(t);
  vein(x, y, a + R(-0.9, 0.9), R(10, 38), R(0.5, 0.9), 1);
}
for (let i = 0; i < 160; i++) {
  const [x, y, a] = edge(R(0, 1)), inset = R(12, 50);
  vein(x + Math.cos(a) * inset, y + Math.sin(a) * inset, R(0, 6.28), R(6, 16), R(0.3, 0.55), 2);
}

// Edge fades: strongest at the rim, gone before the centre box.
const edgeGrads = (id, color, op, depth) => [
  ['t', 0, 0, 0, depth], ['b', 0, H, 0, H - depth], ['l', 0, 0, depth, 0], ['r', W, 0, W - depth, 0],
].map(([s, x1, y1, x2, y2]) => `<linearGradient id="${id}-${s}" gradientUnits="userSpaceOnUse" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"><stop offset="0" stop-color="${color}" stop-opacity="${op}"/><stop offset="1" stop-color="${color}" stop-opacity="0"/></linearGradient>`).join('\n    ');

const svg = `<!-- veins:start (generated by script/dmg/veins.mjs, seed ${seedArg}) -->
  <defs>
    <radialGradient id="vein-fill" gradientUnits="userSpaceOnUse" cx="330" cy="210" r="400" gradientTransform="translate(330 210) scale(1 .64) translate(-330 -210)">
      <stop offset=".46" stop-color="#e5322d" stop-opacity="0"/>
      <stop offset=".7" stop-color="#e5322d" stop-opacity=".55"/>
      <stop offset=".95" stop-color="#ff3b30" stop-opacity=".95"/>
    </radialGradient>
    <radialGradient id="cap-fill" gradientUnits="userSpaceOnUse" cx="330" cy="210" r="400" gradientTransform="translate(330 210) scale(1 .64) translate(-330 -210)">
      <stop offset=".55" stop-color="#ff6b6b" stop-opacity="0"/>
      <stop offset=".9" stop-color="#ff6b6b" stop-opacity=".5"/>
    </radialGradient>
    ${edgeGrads('tinge', '#ff6b6b', 0.14, 80)}
    <!-- Keeps the centre (icons, labels, arrow, hint) and the shine strokes clean. -->
    <filter id="clean-blur" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="14"/></filter>
    <mask id="clean" maskUnits="userSpaceOnUse" x="0" y="0" width="${W}" height="${H}">
      <rect width="${W}" height="${H}" fill="#fff"/>
      <g filter="url(#clean-blur)" fill="#000">
        <rect x="104" y="100" width="452" height="220" rx="40"/>
        <circle cx="566" cy="124" r="34"/>
      </g>
    </mask>
  </defs>
  <g>
    <rect width="${W}" height="${H}" fill="url(#tinge-t)"/>
    <rect width="${W}" height="${H}" fill="url(#tinge-b)"/>
    <rect width="${W}" height="${H}" fill="url(#tinge-l)"/>
    <rect width="${W}" height="${H}" fill="url(#tinge-r)"/>
  </g>
  <g mask="url(#clean)">
    <path fill="url(#cap-fill)" d="${polys.c.join('')}"/>
    <path fill="url(#vein-fill)" d="${polys.v.join('')}"/>
  </g>
  <!-- veins:end -->`;

const html = fs.readFileSync(target, 'utf8');
const next = html.replace(/<!-- veins:start[\s\S]*?<!-- veins:end -->/, svg);
if (next === html && !html.includes(svg)) throw new Error('veins markers not found');
fs.writeFileSync(target, next);
console.log('veins', polys.v.length, 'capillaries', polys.c.length, 'bytes', svg.length);
